email: elcrespo@umich.edu
experimenter: EmmanuelCrespo
project_name: scRNAseq_ventral_analysis
project_path: /nfs/turbo/umms-parent/scRNAseq_ventral_analysis-EmmanuelCrespo-2025-06-05
shared_turbo_directory: /nfs/turbo/umms-parent
